spring:
  datasource:
    url: jdbc:mysql://db:3306/toolroomdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true